version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      DB_TYPE: mysql
      DB_HOST: db              # Must match MySQL service name
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_NAME: multi_tenant_db
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: multi_tenant_db
    ports:
      - "3306:3306"
